GET http://localhost:8080/addstudent
Accept: application/json

###
GET http://localhost:8080/students
Accept: application/json

###
GET http://localhost:8080/students/Maria
Accept: application/json

###


###
